name: wearabouts
description: "A free marketplace for clothes"
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  local_auth: ^2.3.0
  provider: ^6.0.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.6.0
  money_formatter: ^0.0.6
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.3.2
  firebase_analytics: ^11.3.3
  location: ^7.0.1
  google_maps_flutter: ^2.9.0
  latlong2: ^0.9.1
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.4
  json_annotation: ^4.9.0
  build_runner: ^2.3.3
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.1
  dio: ^5.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.8.0
  
  


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/dummyData/users.json
    - assets/dummyData/clothes.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher-web.png"
  adaptive_icon_background: "#38BCA2"
  adaptive_icon_foreground: "assets/icons/t-shirt.jpg"